on: [push]

jobs:
  Restart-Server:
    runs-on: ubuntu-latest
    name: Restart Pebble Host server
    steps:
      - name: Restart Sever
        env:
          RESTART_COMMAND: ${{ secrets.RESTART_COMMAND }}
        run: >
          curl \
            -H "User-Agent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0'" \
            -H "Referer: https://panel.pebblehost.com" \
            -d $RESTART_COMMAND \
            -X POST https://panel.pebblehost.com/api.php
